/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import { GlobalSettings } from './settings';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {GlobalSettings};
export const SettingsSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "defaultDumpDirectory": {
      "type": "string"
    },
    "pgDumpCommand": {
      "type": "string"
    },
    "pgRestoreCommand": {
      "type": "string"
    },
    "psqlCommand": {
      "type": "string"
    }
  },
  "required": [
    "defaultDumpDirectory",
    "pgDumpCommand",
    "pgRestoreCommand",
    "psqlCommand"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isSettings = ajv.compile(SettingsSchema) as ValidateFunction<GlobalSettings>;
export default function validate(value: unknown): GlobalSettings {
  if (isSettings(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isSettings.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Settings'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
